import { v4 as uuidv4 } from "uuid";

interface MockJobEntry {
  title: string;
  salary: string;
  location: string;
  company: string;
  status: string;
  createdat: string;
  id: string;
}
const mockJobEntries: MockJobEntry[] = [
  {
    title: "SWE 2",
    salary: "200000",
    location: "On-site",
    company: "Tesla",
    status: "Accepted",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "190000",
    location: "On-site",
    company: "Tesla",
    status: "Rejected",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "1000",
    location: "On-site",
    company: "Tesla",
    status: "Interviewing",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "108000",
    location: "On-site",
    company: "Tesla",
    status: "Closed",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "10000",
    location: "On-site",
    company: "Tesla",
    status: "Awaiting",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "10000",
    location: "On-site",
    company: "Tesla",
    status: "Awaiting",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "200000",
    location: "On-site",
    company: "Tesla",
    status: "Accepted",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "190000",
    location: "On-site",
    company: "Tesla",
    status: "Rejected",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "1000",
    location: "On-site",
    company: "Tesla",
    status: "Interviewing",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "108000",
    location: "On-site",
    company: "Tesla",
    status: "Closed",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "10000",
    location: "On-site",
    company: "Tesla",
    status: "Awaiting",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "10000",
    location: "On-site",
    company: "Tesla",
    status: "Awaiting",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "200000",
    location: "On-site",
    company: "Tesla",
    status: "Accepted",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "190000",
    location: "On-site",
    company: "Tesla",
    status: "Rejected",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "1000",
    location: "On-site",
    company: "Tesla",
    status: "Interviewing",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "108000",
    location: "On-site",
    company: "Tesla",
    status: "Closed",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "10000",
    location: "On-site",
    company: "Tesla",
    status: "Awaiting",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
  {
    title: "SWE 2",
    salary: "10000",
    location: "On-site",
    company: "Tesla",
    status: "Awaiting",
    createdat: "5/23/2025",
    id: uuidv4(),
  },
];

export default mockJobEntries;
